### ISSUE TITLE
Validate username

### ISSUE THREAD

**Issue by rajivramv** [emqx/emqx-auth-jwt#47]
> The thing here is that if I have a valid JWT token, and if I know another username than my own, I can use this JWT to authenticate as the other user (any user actually, just need one valid JWT)

Is there a work around for this?
_Originally posted by @rajivramv in https://github.com/emqx/emqx-auth-jwt/issues/33#issuecomment-433626275_

**Comment by svrooij** [comment]
Think he means that there is not authentication between the user and the jwt validation. So if you have a valid JWT token you can impersonate every user. Would be nicer to actually check the username with some claim inside the jwt token.

So if you want to login with user `test` the jwt token should have a `sub` claim with the value `test`.

**Comment by Gilbert-Wong** [comment]
Hi, @svrooij  maybe you need this https://jwt.io/

**Comment by masstamike** [comment]
@Gilbert-Wong I think this is a valid concern. In order to test this, sign a jwt with any `sub` value in the payload. Then connect to the broker with a different `username` and the jwt used as `password` from the client during authentication. In the ACL, the `username` passed from the client (not signed in the jwt) will be used.

This means a client only needs a jwt signed by the authority with any valid principle, and can then authenticate to the broker as any user they choose.

**Comment by Gilbert-Wong** [comment]
Thanks for your guys suggestions, this feature would be implemented in 3.1-beta.4.

**Comment by linjunjj** [comment]
Hi @rajivramv @masstamike @svrooij  This feature is designed as follows,  We'll design it like this.

``` 
## Whether to open payload validation
##
## Value: on | off
#auth.jwt.verify_payload = on

## Verify payload content configuration information
##
## Value: String
## auth.jwt.verify_payload.$sub = %c
## auth.jwt.verify_payload.$name = %u
## auth.jwt.verify_payload.$name = secret
##
## For example
#auth.jwt.verify_payload.sub = mysecret
#auth.jwt.verify_payload.name = secret
#auth.jwt.verify_payload.sub = %c
#auth.jwt.verify_payload.sub = %u
```

This is the configuration file  is about how to configure payload validation, The  `auth.jwt.verify_payload` denotes whether validation payload is enabled,  The second configuration item represents the content of validating payload,  `$name` can be any value that represents the key value in JSON in the payload, `secret` denotes the value of validating payload,  `%c` means validating the value of payload with ClientId, And `%u` means validating the value of payload with Username.
Does this design meet your requirements?

**Comment by svrooij** [comment]
I think it would be better to set it up with default values. It might be better to have users opt out of the security settings.

`jwt.username_in = 'name'` that would verify the username is in the `name` claim. In this case the default would be name and the user is able to remove it or set it to some other value in the settings.
You can also do the same for the client id but I wouldn’t set a default value for it.

Stuff inside jwt is never secret because you can extract it (base64 decode).

On other platforms the issuer (`iss`) and the audience (`aud`) are also verified, I would implement that as follows
`jwt.issuer_value = 'some_issuer'`
`jwt.audience_value = 'some_audience'`
If they are set they need to be validated and if they aren’t set they can be missing or container any value.

The issuer is a default claim that is mostly set to the url of the application signing the token. The audience is also a default claim that can be used to set to the application url of the application you expect it to accept the token.

**Comment by HJianBo** [comment]
Hi guys, we have implemented it and released at the v3.1-rc.1.

Thanks for your contribution!

**Comment by and-dzh3** [comment]
Sorry for lame questions but how can I implement this kind of validation of jwt token signed for a specific user?

**Comment by svrooij** [comment]
Check the readme.

```
##
## Value: on | off
auth.jwt.verify_claims = off

## The checklist of claims to validate
##
## Value: String
## auth.jwt.verify_claims.$name = expected
##
## Variables:
##  - %u: username
##  - %c: clientid
# auth.jwt.verify_claims.username = %u

```

**Comment by and-dzh3** [comment]
EMQX_AUTH__JWT__VERIFY_CLAIMS__USERNAME="%u" is ok 
but if you want use any another claim its not working
example :
 EMQX_AUTH__JWT__VERIFY_CLAIMS__PREFERRED_USERNAME="%u" - its not working

**Comment by HJianBo** [comment]
This really won't take effect. This is because when using Docker's environment variables to perform a configuration, it must require that the data line being configured is already present in the configuration file, otherwise it won't take effect.

So, if you are a completely different configuration item, you should either add that configuration manually, or mount the configuration file on an external disk.
